### PR TITLE
Add links to experimental Debian and Ubuntu packages

### PR DESCRIPTION
**Pull request by rhansen**

### CODE REVIEW

**Comment by rvaiya** [comment]
Sorry for taking so long to get around to this. I have rebased and merged it in 7d897a323. Thanks for maintaining these :).

**Comment by David-Else** [comment]
@rhansen Thanks for this! Could you update your repo to the new https://github.com/rvaiya/keyd/releases/tag/v2.5.0 version? Any update on getting this info Debian Trixie? Cheers!

**Comment by rhansen** [comment]
@David-Else Thanks for pinging me.  I'll update my repo some time this week.  I need to do some more work to get the package ready for Debian Trixie; unfortunately I'm not a Debian Developer so the process will take some time.

**Comment by David-Else** [comment]
@rhansen Hello again, I mentioned your package on Reddit and someone wants to help, but there is talk of a 404 on https://mentors.debian.net/package/keyd/ . I don't know if you have a Reddit account, probably a bad idea to use any social media, but I thought I should update you, maybe you can fix the 404? Thanks again for working on this!

**Comment by rhansen** [comment]
@David-Else The package was removed from mentors.debian.net because it is in the process of being uploaded to trixie.  You can still get the package from salsa CI:  https://github.com/rvaiya/keyd/#debian

I'll look into patching it to support gnome-shell 47.

**Comment by David-Else** [comment]
Ah ha, great news! So you don't need help anymore, shall I close the Reddit thread?

**Comment by rhansen** [comment]
Yeah, looks like it's finally moving so that Reddit thread can be closed. I don't know how long it will sit in the new queue, or if a Debian developer can help it move along faster.  For now I think it's best to just wait a few days before following up.

**Pull request closed without merging**
