### PR TITLE
Manpage 2

### PR DESCRIPTION
**Pull request by eNV25**
- use backticks "`" where appropriate
- use tab indent for code block and whitespace changes
- use definition lists for command-line options
- remove `% author` to remove duplicate `AUTHORS` section

### CODE REVIEW

**Comment by rvaiya** [comment]
This looks fine, though I would prefer to avoid using definition lists for the args since it can automatically introduce linebreaks.

**Comment by eNV25** [comment]
I tried looking at the man page using `man -l keyd.1.gz` and there is no line break. It looks like pandoc is smart about this.

**Comment by rvaiya** [comment]
In this case the lines are short enough but they may change at a later
point. I would prefer to use explicit formatting to avoid this. I'm fine
with using them for the config options where the effect is desirable.

**Comment by eNV25** [comment]
I just tested this real quick by copy-pasting a line and that's not the case. There is no line break after the option and everything is properly formatted like a paragraph.

There is only a line break when you have both short option and long option. `**-m**, **--monitor**`.

**Comment by eNV25** [comment]
If you want I can remove the commit and force push anyway.

**Comment by rvaiya** [comment]
> There is only a line break when you have both short option and long option. **-m**, **--monitor**.

So it would seem. In any event, it is non-intuitive behaviour and might cause confusion in future amendments.

> If you want I can remove the commit and force push anyway.

No need, I've already merged your changes and reverted the arg change.

Thanks for making separate commits, however in this case it was probably
unnecessary. These are all related to the man page and don't involve a lot of
superficial formatting changes like the last one, so a single commit is fine.
To this end I've taken the liberty of squashing them.

**Comment by eNV25** [comment]
Thanks for merging.

> To this end I've taken the liberty of squashing them.

Next time you can use Github's "Squash and Merge" feature. This way the PR will show as merged.

**Comment by rvaiya** [comment]
Yes, but I don't know what that actually does and I don't trust/like github
:P.

**Pull request closed without merging**
