### PR TITLE
Simplify install target and remove executable bit from keyd.service in Makefile

### PR DESCRIPTION
**Pull request by eNV25**
Simplify install target and remove executable bit from keyd.service in Makefile

### CODE REVIEW

**Comment by eNV25** [comment]
Do not merge. It the `-t` option is not available in BSDs.

**Comment by rvaiya** [comment]
I've been bitten by portability issues with install before and prefer the explicit mkdirs. The service file probably shouldn't be executable though :P

**Comment by eNV25** [comment]
I thought it would be fine since keyd works only on Linux.

**Comment by rvaiya** [comment]
It should be, but I prefer to keep my projects consistent.

**Pull request merged**
