### PR TITLE
keyd-application-mapper: Apply bindings when title/app id changes on wlroots

### LINKED ISSUE #525: Apply window-specific bindings when the title/class changes on Sway
When I open a window on sway (well, technically [swayfx](https://github.com/WillPower3309/swayfx)), keyd-application-mapper does not apply keybinds with a class expression (at least for pinentry-gtk2 and Librewolf) until I refocus the window. I don't know if this applies to all wlroots-based compositors. I believe this is because the window is focused before the mapper gets the class/app id, as I can see the following events happen if I apply [show-wlroots-events.patch.gz](https://github.com/rvaiya/keyd/files/11917885/show-wlroots-events.patch.gz):
- A new window is opened
- The new window has set its title to pinentry-gtk2
- My terminal is unfocused
- pinentry-gtk2 is focused (this is when the mapper resets keyd and applies window-specific bindings)
- pinentry-gtk2 has set its app id/class to Pinentry-gtk-2

Here are the snippets for the output with the patch applied:

<details>
<summary>Opening pinentry-gtk2</summary>

```
obj: 0x4
event: 0
payload (hex): 050000ff
payload (rep): b'\x05\x00\x00\xff'

obj: 0xff000005 (pinentry-gtk2)
event: 0
payload (hex): 0e00000070696e656e7472792d67746b32000000
payload (rep): b'\x0e\x00\x00\x00pinentry-gtk2\x00\x00\x00'

obj: 0xff000003 (foot)
event: 4
payload (hex): 00000000
payload (rep): b'\x00\x00\x00\x00'

obj: 0xff000005 (pinentry-gtk2)
event: 4
payload (hex): 0400000002000000
payload (rep): b'\x04\x00\x00\x00\x02\x00\x00\x00'

obj: 0xff000005 (pinentry-gtk2)
event: 1
payload (hex): 0f00000050696e656e7472792d67746b2d320000
payload (rep): b'\x0f\x00\x00\x00Pinentry-gtk-2\x00\x00'

obj: 0xff000005 (pinentry-gtk2)
event: 5
payload (hex):
payload (rep): b''

obj: 0xff000003 (foot)
event: 5
payload (hex):
payload (rep): b''
```
</details>

<details>
<summary>Opening LibreWolf</summary>

```
obj: 0x4
event: 0
payload (hex): 050000ff
payload (rep): b'\x05\x00\x00\xff'

obj: 0xff000005 (LibreWolf)
event: 0
payload (hex): 0a0000004c69627265576f6c66000000
payload (rep): b'\n\x00\x00\x00LibreWolf\x00\x00\x00'

obj: 0xff000003 (foot)
event: 4
payload (hex): 00000000
payload (rep): b'\x00\x00\x00\x00'

obj: 0xff000005 (LibreWolf)
event: 4
payload (hex): 0400000002000000
payload (rep): b'\x04\x00\x00\x00\x02\x00\x00\x00'

obj: 0xff000005 (LibreWolf)
event: 1
payload (hex): 0a0000004c69627265576f6c66000000
payload (rep): b'\n\x00\x00\x00LibreWolf\x00\x00\x00'

obj: 0xff000005 (LibreWolf)
event: 5
payload (hex):
payload (rep): b''

obj: 0xff000003 (foot)
event: 5
payload (hex):
payload (rep): b''
```
</details>

### PR DESCRIPTION
**Pull request by the-blank-x**
Fixes #525

### CODE REVIEW

**Comment by the-blank-x** [comment]
There's no 🎉 reaction :(
But yes, still running it, on keyd 2.4.3

**Comment by the-blank-x** [comment]
swayfx 0.3.2, based on sway 1.8.1
I haven't updated my system a month ago though

**Comment by voronind-com** [comment]
@rvaiya Bump. I've been running with this patch for a while now with no issues. Can we merge this? Seems kinda high priority for sway users. Thank you.

**Comment by voronind-com** [comment]
@rvaiya Sorry, but this is still relevant. At least tell me you ack the issue so I can stop pinging. Cheers!

**Comment by rvaiya** [comment]
Thanks for putting some work into this, and apologizes for the unusually long delay. Everything looks good after a review. Rebased and merged in eb6fe4c1.

**Comment by voronind-com** [comment]
@the-blank-x We did it! No more anniversaries tho.

**Pull request closed without merging**
